apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: projetin
data:
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "db"
  DB_PORT: "5432"
  DEBUG: "1"
