apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: projetin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: projetin-frontend
        image: carmelitabraga/projetin-frontend:v1
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c", "npm run setup-prod & npm run start"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: projetin
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
