apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: projetin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: projetin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
