- name: Inicializar Kubernetes no Control-Plane
  hosts: control-plane
  become: true
  tasks:
    - name: Inicializar o Kubernetes control-plane
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init

    - name: Configurar kubectl para o usuario root
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      when: kubeadm_init is changed

    - name: Extrair comando de join do Kubernetes
      command: kubeadm token create --print-join-command
      register: join_command
      when: kubeadm_init is changed

    - name: Salvar comando de join para uso posterior
      local_action: copy content="{{ join_command.stdout }}" dest="/tmp/join_command.txt"
      when: kubeadm_init is changed
